### ISSUE TITLE
cannot startup the program

### ISSUE THREAD

**Issue by niuaniuaniua** [dotbitHQ/das-contracts#13] opened 2021-09-30 08:49 UTC

**Comment by linkdesu** [comment] 2022-01-17 07:34
Hi, sorry for late. We have released the latest version of our project and it's recommand to try the latest version. 

The error you faced is caused by version mismatch between [das-contracts](https://github.com/DeAccountSystems/das-contracts) and [das-types](https://github.com/DeAccountSystems/das-types), and it should be fixed after this release.

**Comment by niuaniuaniua** [comment] 2022-03-30 09:29
.

**Closed** 2022-03-30 09:28 UTC
